[package]
name = "fuzzrs"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = { version = "0.4.28", features = ["kv"] }
pest = "2.8.3"
pest_derive = "2.8.3"
structopt = "0.3.26"

[profile.release-with-debug]
inherits = "release"
debug = true
